apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drain-machine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drain-machine.name" . }}
    helm.sh/chart: {{ include "drain-machine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "drain-machine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drain-machine.name" . }}
    helm.sh/chart: {{ include "drain-machine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - drain-machine-status
  verbs:
  - get
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "drain-machine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drain-machine.name" . }}
    helm.sh/chart: {{ include "drain-machine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "drain-machine.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "drain-machine.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "drain-machine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drain-machine.name" . }}
    helm.sh/chart: {{ include "drain-machine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "drain-machine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drain-machine.name" . }}
    helm.sh/chart: {{ include "drain-machine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "drain-machine.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "drain-machine.fullname" . }}
    namespace: {{ .Release.Namespace }}
